<?php

declare(strict_types=1);

/**
 * Implements hook_preprocess_HOOK().
 */
function file_improvements_preprocess_file_link(array &$variables): void {
  /** @var \Drupal\file_improvements\HookHandlers\PreprocessHandlers\PreprocessFileLinkHandler $service */
  $service = \Drupal::service('file_improvements.hook_handlers.preprocess_file_link');

  $service->preprocess($variables);
}

/**
 * Implements hook_theme_registry_alter().
 */
function file_improvements_theme_registry_alter(array &$themeRegistry) {
  /** @var \Drupal\file_improvements\HookHandlers\ThemeRegistryAlterHandler $service */
  $service = \Drupal::service('file_improvements.hook_handlers.theme_registry_alter');

  $service->alter($themeRegistry);
}
